### ISSUE TITLE
Undefined Object does not understand #keysAndValuesDo: on WebBrowserView example

### ISSUE THREAD

**Issue by Zenchess** [JBetz/Dolphin-CEF#1]
Hi.  I'm trying to run WebBrowserView example.  I've installed all the requirements and have both the sdl and cef packages installed.  

I get a debugger at CefClient initialize

in the part : 

self class callbackRegistry 
     keysAndValuesDo: [:aSymbol :aCallback | self perform: aSymbol with: aCallback asParameter].

the code "self class callbackRegistry" is nil.  I noticed in the code that this variable CallbackRegistry gets set in onStartup of ExtendedExternalStructure and I'm guessing this doesn't get called?

**Comment by JBetz** [comment]
Hi @Zenchess, thanks for reporting the issue!

> the code "self class callbackRegistry" is nil. I noticed in the code that this variable CallbackRegistry gets set in onStartup of ExtendedExternalStructure and I'm guessing this doesn't get called?

Yes, that sounds right. The `onStartup` doesn't get called the first time you load the package, so the callback registeries don't get initialized. Which means I need to add a call to `onStartup` inside of `ExtendedExternaStructure class>>initialize` to correctly handle the first session. I'll push a fix for that now.
