### ISSUE TITLE
How can I inject javascript into the page?

### ISSUE THREAD

**Issue by Zenchess** [JBetz/Dolphin-CEF#2]
Sorry for this being an issue, I didn't see a discussion page.  Is it possible to execute javascript into the page with this package?  I did some searching through the methods but didn't find anything definite that would allow me to do that.

**Comment by Zenchess** [comment]
webbrowser := WebBrowserView example.
browser := webbrowser chromiumBrowser.

cefBrowser := browser cefBrowser.

mainFrame := cefBrowser getMainFrame.

mainFrame executeJavaScript_code: 'window.alert("hello"' scriptUrl: nil startLine: nil.

This is what I've tried so far.  Whenever I do the executeJavaScript_code: scriptUrl: startLine: method though, the image crashes.

**Comment by Zenchess** [comment]
I've tried mainFrame executeJavaScript_code: 'window.alert("hello");' scriptUrl: '' startLine: 0
image still crashes

**Comment by JBetz** [comment]
`CefFrame>>executeJavaScript_code:scriptUrl:startLine:` is a raw CEF method call, so any string arguments need to be converted into a CefString.

So for your code snippet:

```smalltalk 
mainFrame executeJavaScript_code: 'window.alert("hello")' asCefString scriptUrl: nil startLine: nil
```

But yeah, this could definitely use a higher level interface that handles all the string conversions. I'll push a fix for that shortly.

> Sorry for this being an issue, I didn't see a discussion page. 

No problem. I just enabled Discussions on the repo so it should be accessible now.

**Comment by Zenchess** [comment]
Thanks!  It works now using 'asCefString.  

Is there a way to get a return from executing some javascript?  Like if i executed 5+5 it would return 10?

**Comment by Zenchess** [comment]
It looks like what I need is a method that gives me the console output.  Looking for one but not finding it.  I saw some old post from 2010 that mentioned CefHandler but I don't think that's up to date

**Comment by Zenchess** [comment]
Ok, after more research it looks like I need to use on_console_message in CefDisplayHandler.  not sure how I can get that to give me text though, as on_console_message: seems to just take an integer?

**Comment by JBetz** [comment]
> Is there a way to get a return from executing some javascript? Like if i executed 5+5 it would return 10?

There is, but it isn't straightforward and would need to be asynchronous. Javascript runs in separate system processes (called Render processes) from Dolphin (the Browser process), so CEF uses an IPC protocol to communicate between them.

Basic idea is to use `CefFrame>>sendProcessMessage:targetProcess:message:` to send Javascript source code to the corresponding Render process, then set up a handler that runs the Javascript and sends the result back to the Browser process via the same interface.

The handler would need to be added to CefSubprocessRunner, which is a small C++ executable. It's already doing something similar for pushing mouse over events to Dolphin (https://github.com/JBetz/CefSubprocessRunner/blob/main/src/client_app_renderer.cc#L105) which are handled in `ChromiumBrowser>>onProcessMessageReceived` (https://github.com/JBetz/Dolphin-CEF/blob/master/Chromium%20Embedded%20Framework/ChromiumBrowser.cls#L378-L384).

So yeah, it would require probably a dozen lines of C++ but should be doable. I haven't had a need for it yet, but it would be nice to have.

**Comment by JBetz** [comment]
> Ok, after more research it looks like I need to use on_console_message in CefDisplayHandler.

Nice, that will be much simpler.

> not sure how I can get that to give me text though, as on_console_message: seems to just take an integer?

I hadn't implemented the callback for `on_console_message` yet, so the integer is basically a placeholder.

If you look in `CefDisplayHandler class>>defineFields` you can see which callbacks have actually been implemented. Any field that looks like a callback or method name with a DWORDField or LPVOIDField type is probably unimplemented.

Here's what it looks like to implement `on_console_message`: https://github.com/JBetz/Dolphin-CEF/commit/756a24a37f32da37fe5094ab42e49360dec3caef

So to see the console logs, you'll just need to implement `ChromiumBrowser>>onConsoleMessage:browser:level:message:source:line:` or forward it to the host view.

**Comment by Zenchess** [comment]
great, that worked perfect.  I can now specify in the scriptUrl part of executeJavaScript_code:  something like: app://smalltalk/workspace.js' and then I can look for that in the "source" parameter of chromiumBrowser onConsoleMessage.  Thanks a lot!

**Comment by JBetz** [comment]
No problem!

**Comment by JBetz** [comment]
A cleaner method for evaluating JavaScript code and getting a result has been implemented in: https://github.com/JBetz/Dolphin-CEF/commit/c3a85d1e2615fc35bf84b0e65d114c7ee0b9ecc2

Example:
```smalltalk
chromiumBrowser evalJavaScript: '1 + 1' callback: [ :result | result inspect ]
```

`result` will contain a parsed JSON value. If the JavaScript code throws an exception, a `CefJavaScriptException` will be raised, which has an error message as well as source location (see https://magpcss.org/ceforum/apidocs3/projects/(default)/CefV8Exception.html for the corresponding CEF class).
