### ISSUE TITLE
Invalid PAX file

### ISSUE THREAD

**Issue by Zenchess** [JBetz/Dolphin-CEF#3]
using a fresh install of Dolphin 7.20 , git cloned the repo, tried to install Chromium Embedded Framework pax file.
Get the error: "Invalid PAX file"
Package class(Object) error: 
errorInvalidPAXFile:

In the meanwhile I see all the classes are in the folder, so I will try loading all of them.

I noticed in the PAX file there are "imageStripperBytes" - does this have something to do with it?  Or maybe you saved the PAX file with a different version of dolphin?

**Comment by Zenchess** [comment]
I am starting to feel like I am doing something horribly wrong like checking out the files in the wrong format or something...

**Comment by JBetz** [comment]
I think this is due to SDL not being listed as a prerequisite even though #onAudioStreamStarted: referenced it, ~and/or the FFI Extensions package not having been saved in the new package file format for Dolphin 7.2~.

So, I've removed the dependency on SDL and updated the FFI Extensions pax files on `master`. Just tried loading the Chromium Embedded Framework pax file into fresh 7.2 image and it succeeds with no error.

@Zenchess Can you update your checkout to the latest on `master` and retry?

**Comment by Zenchess** [comment]
It worked.  But when I ran the webbrowser example I got an error because string does not understand spec.  I changed the method to this: 
createWindowedBrowser: aUrl rectangle: aRectangle window: aHandle
	| windowInfo browserSettings resultCode |
	CefBrowserProcessRunner ensureRunning.
	windowInfo := CefWindowInfo new
				style: self cefWindowStyle;
				ex_style: self cefWindowExStyle;
				parent_window: aHandle;
				bounds: aRectangle asCefRect.
	browserSettings := CefBrowserSettings new.
	self initializeWindowedClient.
	resultCode := self library
				browserHostCreateBrowser_windowInfo: windowInfo
				client: cefClient
				url: aUrl asUrl spec asCefString
				settings: browserSettings
				extraInfo: nil
				requestContext: nil.
	resultCode = 0 ifTrue: [Error signal: 'Error creating CEF browser']
	
	and it worked.
	
	and just in case i changed my checkouts to 'as is' so I don't get weird windows>linux conversions when checking out just in case

**Comment by JBetz** [comment]
Ah, that's a bug. It should work with either a String or a Url. I'll patch that later today.

**Comment by JBetz** [comment]
Original issue fixed in: https://github.com/JBetz/Dolphin-CEF/commit/a32df8ff1cce03265142161b4f91538268be9e7b

URL issue fixed in: https://github.com/JBetz/Dolphin-CEF/commit/2bb20f29cf521dd15ee607a31ba3040e6e16a562
